##Comando para instalar as dependências do projeto
  --pip install -r .\src\requirements.txt

##Comando para executar testes unitários do projeto
  --pytest -v src/test

##Comando par executar o Flake8 para formatar o código projeto
  --flake8 --max-line-length=110 src
